### ISSUE TITLE
Is there any way to know on a containerd level to which pod a container belongs to?

### ISSUE THREAD

**Issue by vburenin** [containerd/cri-containerd#512]
By default, containerd runs containers locally using runc, however there are projects which are spinning up each container as a separate VM. This behavior doesn't fit k8s pod concept, since containers do not share same memory, FS, etc. To fix it pod containers should run on the same VM. However, if containerd can't know to which pod container belongs to, so it will not know if it needs a new VM or it can use an existing VM. Theoretically, it could be done via container labels, or something, so custom containerd plugins could see more placement info for containers.

**Comment by vburenin** [comment]
I guess I could use these container labels:
io.kubernetes.pod.name
io.kubernetes.pod.namespace
io.kubernetes.pod.uid

It might be not very reliable long term if labels are changed in the future, but should be fine for now.

**Comment by yanxuean** [comment]
These labels be passed over CRI, them should be reliable.

**Comment by Random-Liu** [comment]
> It might be not very reliable long term if labels are changed in the future, but should be fine for now.

Yeah, we don't expect user to rely on the labels, although there are users doing that.

> By default, containerd runs containers locally using runc, however there are projects which are spinning up each container as a separate VM. This behavior doesn't fit k8s pod concept, since containers do not share same memory, FS, etc. To fix it pod containers should run on the same VM. However, if containerd can't know to which pod container belongs to, so it will not know if it needs a new VM or it can use an existing VM. Theoretically, it could be done via container labels, or something, so custom containerd plugins could see more placement info for containers.

@vburenin I believe the behavior you mentioned should happen in cri-containerd instead of containerd. There are several reasons:
1) Containerd only accept a OCI runtime spec, and use it to talk to OCI runtime to create container. It's cri-containerd compose the runtime spec based on pod/container config.
2) The [katacontainers](https://katacontainers.io/) people are working on adding support in cri-containerd now https://github.com/kubernetes-incubator/cri-containerd/pull/504. It seems similar with what you are asking for. :)
3) In Kubenretes sig-node, we'll work on secure pod definition next year. It also include how to properly define and configure a VM-based pod (e.g. katacontainers). There will be API defined at both Kubernetes level and container runtime interface level. When that happens, you don't need to rely on labels or annotations, you'll be able to use API directly. When that comes out, we'll also integrate with that API in cri-containerd.

It seems that you'll be interested in the secure pod API discussion. Join the sig-node meeting if you are. :)

**Comment by vburenin** [comment]
@Random-Liu Thank you so much for that extensive answer. It feels like I am right on time here. At the moment I am mostly working on PoC for some ideas and prototypes, but it feels like it is going to go way beyond that after holidays.

So yes, I am very interested in the secure pod API discussion. I will try to make it on Tuesday next week.

**Comment by Random-Liu** [comment]
@vburenin Next signode meeting will be Janurary 2nd. I think we'll discuss about 2018 plans on that meeting.

**Comment by Random-Liu** [comment]
@vburenin I think Jan 2nd signode meeting is cancelled, because most of people are still on vocation. Feel free to join the next one.

**Comment by Random-Liu** [comment]
@vburenin Can we close this one? :)

**Comment by vburenin** [comment]
I think so.
